/***************************
TEST 15
***************************/
#include "../mtmflix.h"
#include "test_utilities.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "testGenerator.h"

static bool test15(){
	FILE* f12 = fopen("diff/out15", "w");
	ASSERT_TEST(f12);
	MtmFlix m = mtmFlixCreate();

	ASSERT_TEST(mtmFlixAddSeries(m, "s0", 55, 5, agesOver, 73) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s1", 67, 0, agesAll, 33) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s2", 21, 1, agesGrand, 41) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s3", 74, 6, agesUnder, 166) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s4", 54, 2, agesUnder, 177) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s5", 7, 5, agesGrand, 137) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s6", 12, 6, agesAll, 106) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s7", 1, 0, agesAdult, 61) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s8", 56, 1, agesAll, 78) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s9", 10, 6, agesAll, 113) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s10", 53, 6, agesAll, 141) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s11", 47, 3, agesOver, 1) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s12", 63, 6, agesAll, 1) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s13", 54, 0, agesAll, 99) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s14", 34, 3, agesGrand, 113) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s15", 10, 5, agesAll, 40) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s16", 56, 7, agesAll, 61) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s17", 78, 3, agesAll, 81) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u0", 115) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u1", 25) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u2", 80) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u3", 65) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u4", 25) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u5", 120) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u6", 70) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u7", 105) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u8", 115) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u9", 50) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u10", 10) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u11", 105) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u12", 25) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u13", 40) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u14", 45) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u15", 30) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u16", 30) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u17", 115) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u18", 25) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u19", 85) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u20", 70) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u13") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u11") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u3") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u15") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u16") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u15") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u13") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u9") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u17") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u4") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u7") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u14") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u11") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u7") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u8") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u0") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s7") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s7") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s2") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s5") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s7") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s0") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s14") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s5") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s7") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s7") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s7") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s7") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s7") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s14") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s2") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s2") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s5") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s2") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s7") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s7") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s0") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s0") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s2") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s14") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s5") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s14") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s14") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s2") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s14") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s5") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s14") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s0") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s5") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s5") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s0") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s5") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s7") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s7") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixRemoveUser(m, "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixRemoveUser(m, "u0") == MTMFLIX_USER_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixRemoveSeries(m, "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixRemoveSeries(m, "s3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixReportSeries(m, 0, f12) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixReportUsers(m, f12) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u0", 0, f12) == MTMFLIX_USER_DOES_NOT_EXIST);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u1", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u2", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u3", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u4", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u5", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u6", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u7", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u8", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u9", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u10", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u11", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u12", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u13", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u14", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u15", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u16", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u17", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u18", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u19", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u20", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s14") == MTMFLIX_USER_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s9") == MTMFLIX_USER_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s11") == MTMFLIX_USER_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s10") == MTMFLIX_USER_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s16") == MTMFLIX_USER_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s6") == MTMFLIX_USER_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s8") == MTMFLIX_USER_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s11") == MTMFLIX_USER_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s13") == MTMFLIX_USER_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s15") == MTMFLIX_USER_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s17") == MTMFLIX_USER_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s16") == MTMFLIX_USER_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s5") == MTMFLIX_USER_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s3") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s9") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s3") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s9") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s3") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s3") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s3") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixReportSeries(m, 0, f12) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixReportUsers(m, f12) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u0", 0, f12) == MTMFLIX_USER_DOES_NOT_EXIST);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u1", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u2", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u3", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u4", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u5", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u6", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u7", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u8", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u9", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u10", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u11", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u12", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u13", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u14", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u15", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u16", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u17", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u18", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u19", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u20", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");

	fclose(f12);
	mtmFlixDestroy(m);
	return true;
}

int main(){
	RUN_TEST(test15);
	return 0;
}
