/***************************
TEST 16
***************************/
#include "../mtmflix.h"
#include "test_utilities.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "testGenerator.h"

static bool test16(){
	FILE* f12 = fopen("diff/out16", "w");
	ASSERT_TEST(f12);
	MtmFlix m = mtmFlixCreate();

	ASSERT_TEST(mtmFlixAddSeries(m, "s0", 81, 4, agesAdult, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s1", 73, 4, agesGrand, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s2", 78, 1, agesOver, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s3", 25, 5, agesGrand, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s4", 27, 1, agesGrand, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s5", 31, 0, agesAll, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s6", 42, 4, agesAll, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s7", 21, 4, agesAll, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s8", 66, 1, agesAll, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s9", 78, 2, agesAdult, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s10", 59, 2, agesAll, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s11", 8, 6, agesOver, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s12", 16, 0, agesAdult, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s13", 11, 4, agesUnder, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s14", 5, 2, agesGrand, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s15", 58, 0, agesGrand, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s16", 80, 2, agesAll, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddSeries(m, "s17", 68, 6, agesAll, 20) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u0", 85) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u1", 60) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u2", 100) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u3", 80) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u4", 50) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u5", 30) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u6", 40) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u7", 100) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u8", 45) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u9", 105) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u10", 55) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u11", 115) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u12", 115) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u13", 35) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u14", 35) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u15", 50) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u16", 65) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u17", 55) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u18", 10) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u19", 5) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddUser(m, "u20", 30) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u0", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u11") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u18") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u0") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u1", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u2", "u20") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u3") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u3", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u10") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u4", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u5", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u6", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u7", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u8", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u9", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u0") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u1") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u10", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u17") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u11") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u3") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u11", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u15") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u12", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u8") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u11") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u13", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u19") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u14") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u15") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u2") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u14", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u3") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u15", "u0") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u16", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u8") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u17", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u20") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u18") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u18", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u20") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u19") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u19", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u15") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u1") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u20") == MTMFLIX_SUCCESS);
	//ASSERT_TEST(mtmFlixAddFriend(m, "u20", "u20") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s13") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s13") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u0", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u1", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s0") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s0") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s0") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u2", "s13") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s9") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s9") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s13") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s12") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s9") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u3", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s15") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s15") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u4", "s14") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s14") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s14") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u5", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s13") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s1") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u6", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s13") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s0") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s13") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u7", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s2") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s15") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s1") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s13") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u8", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s9") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s0") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u9", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s13") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u10", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s0") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s0") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s13") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u11", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s12") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s13") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s9") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s9") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s9") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u12", "s13") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s15") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s2") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s2") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u13", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s15") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s1") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s15") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u14", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s15") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u15", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s13") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u16", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s15") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s1") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s1") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u17", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s9") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s2") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s1") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s0") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s0") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s15") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s9") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u18", "s12") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s15") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s12") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s3") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s12") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s14") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s4") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s11") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s2") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u19", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s1") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s1") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s14") == MTMFLIX_USER_NOT_IN_THE_RIGHT_AGE);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesJoin(m, "u20", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixRemoveUser(m, "u11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixRemoveUser(m, "u14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixRemoveSeries(m, "s12") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixRemoveSeries(m, "s0") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixReportSeries(m, 0, f12) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixReportUsers(m, f12) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u0", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u1", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u2", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u3", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u4", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u5", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u6", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u7", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u8", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u9", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u10", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u11", 0, f12) == MTMFLIX_USER_DOES_NOT_EXIST);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u12", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u13", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u14", 0, f12) == MTMFLIX_USER_DOES_NOT_EXIST);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u15", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u16", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u17", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u18", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u19", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u20", 0, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s12") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u0", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s5") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s12") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s12") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u3", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s12") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s12") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s12") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u6", "s3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s0") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s1") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u9", "s0") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s13") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s12") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s2") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s0") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u12", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s14") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s11") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s16") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s12") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s3") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u15", "s0") == MTMFLIX_SERIES_DOES_NOT_EXIST);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s7") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s8") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s17") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s10") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s9") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s4") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s15") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixSeriesLeave(m, "u18", "s6") == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixReportSeries(m, 0, f12) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixReportUsers(m, f12) == MTMFLIX_SUCCESS);
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u0", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u1", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u2", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u3", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u4", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u5", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u6", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u7", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u8", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u9", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u10", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u11", 1, f12) == MTMFLIX_USER_DOES_NOT_EXIST);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u12", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u13", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u14", 1, f12) == MTMFLIX_USER_DOES_NOT_EXIST);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u15", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u16", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u17", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u18", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u19", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");
	ASSERT_TEST(mtmFlixGetRecommendations(m, "u20", 1, f12) == MTMFLIX_SUCCESS);
	fprintf(f12, "***********************\n");

	fclose(f12);
	mtmFlixDestroy(m);
	return true;
}

int main(){
	RUN_TEST(test16);
	return 0;
}
